language: java
jdk:
- oraclejdk8
- oraclejdk7
- openjdk7
env:
  global:
  - secure: OPho7nWDYZ4hpMRyrZ+UBVBfMy18C+8H2qLk5/2zVgm63UurNg1RUXJyn58uEi6lBAdeaHuAKyJ6pCu7VkY32fCXJTx5NIOzK02rNqdNSZGdIvmcXqMaJkCFTN31vJXSsrUNBXEzVWK3d/4l5fjEw84Fc9x0UrWoWo8A+VipZmY=
sudo: false
after_success:
- .buildscript/push-site-to-gh-pages.sh
cache:
  directories:
  - "$HOME/.m2"
