language: java
jdk:
- oraclejdk7
- openjdk7
- openjdk6
env:
  global:
  - GEOCACHING_STAGING=false
  - secure: mLYxDjI9JKqgttpeq/XwDHVaqRG2Uvgt2R5rwBtjxWwOSXsarM47LOu+a0nKEpd/ND2QckAS+GOnl7FPtx5RIk3jr2FfRXBzyB+Fn7Xh3VM4zHMRGCfknOGaInNoXB2WFBRrNW0TUHdTOizm0rCP0J5z416EV+QRQmZjOpXyXFA=
sudo: false
