language: java
jdk:
- oraclejdk8
- oraclejdk7
- openjdk7
env:
  global:
  - secure: "Da5O7EwUpNhqTIKef2CqWGqCzV+TjJtOh1doobxMmLV6zp4IrZ8NI4vNPmLWpvMc+HejrEUVvmhkt8//9/FgAk1tqzdXJm2S9hSfXG4fLb+D32Icl7/kIrSfS17nlqSbCqxrAQzTQnGiglsVAiEiuR/c1i+a4WTepRlr36LhhYo="
sudo: false
after_success:
- .buildscript/push-site-to-gh-pages.sh
cache:
  directories:
  - "$HOME/.m2"
