language: java
jdk:
- oraclejdk7
- openjdk7
- openjdk6
env:
  global:
  - GEOCACHING_STAGING=false
  - secure: DixRMwI3J/OQngkEa+UBf5hve9+sB0KC5hjOmB9ICaZXoDx8VnaCR2Bnniw25tzlgEIkhMxdFcxLFatbxc63GMM4RmaaKMlHeqMbMMbnsjSq8jgeq/kh49hDixsiltH2YlCGh9bh1E1uIckG4tsHEmrCaqnEKW0qkMxBWDNXIcg=
sudo: false
